import type { AccountSettings, EntryMethod, MarketIdea, ResultStatus, TechnicalStatus, TradeArgument } from "@/types/trade-gate";
import { DEFAULT_INSTRUMENT_SYMBOL } from "./instrumentDefaults";

export const STORAGE_KEY = "trade-gate-state-v1";

export const LOSS_LIMIT = -1000;

export const DEFAULT_DAILY_RISK_BUDGET = "1000";

export const MAX_INSTRUMENT_IMAGE_BYTES = 750_000;

export const DEFAULT_ACCOUNT_SETTINGS: AccountSettings = {
  accountSize: "100000",
  propDailyLossLimit: "5000",
  personalDailyStop: "1000",
  maxLossLimit: "10000",
  personalMaxLoss: "3000",
  profitTarget: "10000",
};

const DEFAULT_ARGUMENT_DATE = "2026-01-01T00:00:00.000Z";

export const DEFAULT_TRADE_ARGUMENTS: TradeArgument[] = [
  {
    id: "false-breakout-reclaim",
    name: "False breakout reclaim",
    description: "Цена выносит уровень, возвращается обратно и подтверждает, что пробой был ложным.",
    category: "Reclaim",
    tags: ["false-breakout", "reclaim"],
    defaultInstrument: DEFAULT_INSTRUMENT_SYMBOL,
    isDefault: true,
    isActive: true,
    createdAt: DEFAULT_ARGUMENT_DATE,
    updatedAt: DEFAULT_ARGUMENT_DATE,
  },
  {
    id: "liquidity-sweep-htf-level",
    name: "Liquidity sweep at HTF level",
    description: "Снятие ликвидности на старшем уровне с подтверждённым возвратом в структуру.",
    category: "Liquidity",
    tags: ["liquidity", "htf"],
    defaultInstrument: "",
    isDefault: true,
    isActive: true,
    createdAt: DEFAULT_ARGUMENT_DATE,
    updatedAt: DEFAULT_ARGUMENT_DATE,
  },
  {
    id: "compression-breakout-volume",
    name: "Compression breakout with volume",
    description: "Сжатие волатильности перед пробоем, подтверждённое объёмом или импульсом.",
    category: "Breakout",
    tags: ["compression", "volume"],
    defaultInstrument: "",
    isDefault: true,
    isActive: true,
    createdAt: DEFAULT_ARGUMENT_DATE,
    updatedAt: DEFAULT_ARGUMENT_DATE,
  },
  {
    id: "impulse-continuation-reclaim",
    name: "Impulse continuation after reclaim",
    description: "Импульс подтверждает смену контроля, затем рынок удерживает reclaim-зону.",
    category: "Continuation",
    tags: ["impulse", "continuation"],
    defaultInstrument: "",
    isDefault: true,
    isActive: true,
    createdAt: DEFAULT_ARGUMENT_DATE,
    updatedAt: DEFAULT_ARGUMENT_DATE,
  },
  {
    id: "retest-failed-breakdown",
    name: "Retest after failed breakdown",
    description: "Пробой вниз не получает продолжения, а ретест подтверждает возврат покупателей.",
    category: "Retest",
    tags: ["failed-breakdown", "retest"],
    defaultInstrument: "",
    isDefault: true,
    isActive: true,
    createdAt: DEFAULT_ARGUMENT_DATE,
    updatedAt: DEFAULT_ARGUMENT_DATE,
  },
  {
    id: "exhaustion-wick-resistance",
    name: "Exhaustion wick into resistance",
    description: "Вынос в сопротивление с фитилём истощения и слабым продолжением.",
    category: "Exhaustion",
    tags: ["exhaustion", "resistance"],
    defaultInstrument: "",
    isDefault: true,
    isActive: true,
    createdAt: DEFAULT_ARGUMENT_DATE,
    updatedAt: DEFAULT_ARGUMENT_DATE,
  },
  {
    id: "trend-continuation-pullback",
    name: "Trend continuation after pullback",
    description: "Тренд остаётся структурно целым, вход после контролируемого pullback.",
    category: "Continuation",
    tags: ["trend", "pullback"],
    defaultInstrument: "",
    isDefault: true,
    isActive: true,
    createdAt: DEFAULT_ARGUMENT_DATE,
    updatedAt: DEFAULT_ARGUMENT_DATE,
  },
  {
    id: "news-overreaction-fade",
    name: "News overreaction fade",
    description: "Новостной импульс выглядит перегретым и теряет продолжение после первого расширения.",
    category: "News",
    tags: ["news", "fade"],
    defaultInstrument: "",
    isDefault: true,
    isActive: true,
    createdAt: DEFAULT_ARGUMENT_DATE,
    updatedAt: DEFAULT_ARGUMENT_DATE,
  },
  {
    id: "oil-impulse-retest",
    name: "Oil impulse retest",
    description: "Импульс по нефти с контролируемым ретестом зоны, где риск и invalidation заранее понятны.",
    category: "Retest",
    tags: ["oil", "impulse", "retest"],
    defaultInstrument: "UKOIL.cash",
    isDefault: true,
    isActive: true,
    createdAt: DEFAULT_ARGUMENT_DATE,
    updatedAt: DEFAULT_ARGUMENT_DATE,
  },
  {
    id: "range-rejection",
    name: "Range rejection",
    description: "Отбой от границы диапазона с подтверждением, что рынок не принимает цену за уровнем.",
    category: "Range",
    tags: ["range", "rejection"],
    defaultInstrument: "",
    isDefault: true,
    isActive: true,
    createdAt: DEFAULT_ARGUMENT_DATE,
    updatedAt: DEFAULT_ARGUMENT_DATE,
  },
  {
    id: "liquidity-sweep",
    name: "Liquidity sweep",
    description: "Сбор ликвидности за уровнем с возвратом и понятной точкой отмены идеи.",
    category: "Liquidity",
    tags: ["liquidity", "sweep"],
    defaultInstrument: "",
    isDefault: true,
    isActive: true,
    createdAt: DEFAULT_ARGUMENT_DATE,
    updatedAt: DEFAULT_ARGUMENT_DATE,
  },
  {
    id: "breakout-retest",
    name: "Breakout + retest",
    description: "Пробой уровня получает ретест и удержание, вход строится от подтверждённой зоны.",
    category: "Breakout",
    tags: ["breakout", "retest"],
    defaultInstrument: "",
    isDefault: true,
    isActive: true,
    createdAt: DEFAULT_ARGUMENT_DATE,
    updatedAt: DEFAULT_ARGUMENT_DATE,
  },
  {
    id: "news-spike-fade",
    name: "News spike fade",
    description: "Новостной вынос теряет продолжение, а вход опирается на затухание импульса.",
    category: "News",
    tags: ["news", "fade"],
    defaultInstrument: "",
    isDefault: true,
    isActive: true,
    createdAt: DEFAULT_ARGUMENT_DATE,
    updatedAt: DEFAULT_ARGUMENT_DATE,
  },
  {
    id: "trend-continuation",
    name: "Trend continuation",
    description: "Продолжение действующего тренда после паузы, pullback или reclaim ключевой зоны.",
    category: "Continuation",
    tags: ["trend", "continuation"],
    defaultInstrument: "",
    isDefault: true,
    isActive: true,
    createdAt: DEFAULT_ARGUMENT_DATE,
    updatedAt: DEFAULT_ARGUMENT_DATE,
  },
  {
    id: "countertrend-scalp",
    name: "Countertrend scalp",
    description: "Короткая контртрендовая идея только при ясном уровне, ограниченном риске и быстром invalidation.",
    category: "Scalp",
    tags: ["countertrend", "scalp"],
    defaultInstrument: "",
    isDefault: true,
    isActive: true,
    createdAt: DEFAULT_ARGUMENT_DATE,
    updatedAt: DEFAULT_ARGUMENT_DATE,
  },
];

export const DEFAULT_ENTRY_METHODS: EntryMethod[] = [
  "Retest",
  "Breakout",
  "False breakout",
  "Pullback",
  "Momentum continuation",
  "Liquidity sweep",
  "Volume confirmation",
  "News reaction",
  "Level rejection",
  "Wolfe wave entry",
  "Manual confirmation",
].map((name) => ({
  id: name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, ""),
  name,
  description: "",
  isDefault: true,
  isActive: true,
  createdAt: DEFAULT_ARGUMENT_DATE,
  updatedAt: DEFAULT_ARGUMENT_DATE,
}));

export const MARKET_IDEAS: MarketIdea[] = [
  {
    symbol: "UKOIL.cash",
    title: "Нефть",
    bias: "Приоритет лонг выше 86 при удержании импульса",
    scenario: "Шорт только если будет агрессивный слив под локальный минимум диапазона",
  },
  {
    symbol: "XAUUSD",
    title: "Золото",
    bias: "Следить за реакцией на новости и удержанием дневного тренда",
    scenario: "Лучше торговать только после подтверждения объёмом",
  },
  {
    symbol: "COCOA.c",
    title: "Какао",
    bias: "Высокая волатильность — только минимальный риск",
    scenario: "Интересен пробой после накопления",
  },
];

export const RESULT_STATUS_LABELS: Record<ResultStatus, string> = {
  not_taken: "Входа не было",
  no_entry: "Без входа",
  take: "Тейк",
  stop: "Стоп",
  manual_profit: "Ручное закрытие в плюс",
  manual_loss: "Ручное закрытие в минус",
  breakeven: "Безубыток",
};

export const TECHNICAL_STATUS_LABELS: Record<TechnicalStatus, string> = {
  yes: "Да",
  no: "Нет",
  partial: "Частично",
};
